
import { Product, Category, Brand, Campaign } from './types';

// ==================== MARKALAR ====================
export const BRANDS: Brand[] = [
  { id: 'royal-canin', name: 'Royal Canin', slug: 'royal-canin', logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg' },
  { id: 'hills', name: "Hill's", slug: 'hills', logo_url: '/marka_fotograflari/Hill_s/000001.jpg' },
  { id: 'acana', name: 'Acana', slug: 'acana', logo_url: '/marka_fotograflari/Acana/000001.jpg' },
  { id: 'proplan', name: 'Pro Plan', slug: 'proplan', logo_url: '/marka_fotograflari/Purina%20Pro%20Plan/000001.jpg' },
  { id: 'nd', name: 'N&D Farmina', slug: 'nd', logo_url: '/marka_fotograflari/Farmina/000001.jpg' },
  { id: 'orijen', name: 'Orijen', slug: 'orijen', logo_url: '/marka_fotograflari/Orijen/000001.jpg' },
  { id: 'brit-care', name: 'Brit Care', slug: 'brit-care', logo_url: '/markalar/brit.png' },
  { id: 'felicia', name: 'Felicia', slug: 'felicia', logo_url: '/markalar/felicia.png' },
  { id: 'reflex', name: 'Reflex', slug: 'reflex', logo_url: '/markalar/Group_135141.webp' },
  { id: 'jungle', name: 'Jungle', slug: 'jungle', logo_url: '/markalar/Group_135142.avif' },
  { id: 'enjoy', name: 'Enjoy', slug: 'enjoy', logo_url: '/markalar/Group_135146.avif' },
  { id: 'bestpet', name: 'BestPet', slug: 'bestpet', logo_url: '/markalar/Group_135148.webp' },
  { id: 'dogido', name: 'Dogido', slug: 'dogido', logo_url: '/markalar/Group_135149.webp' },
  { id: 'proline', name: 'ProLine', slug: 'proline', logo_url: '/markalar/Group_135152.webp' },
  { id: 'ever-clean', name: 'Ever Clean', slug: 'ever-clean', logo_url: '/markalar/ever-clean.webp' },
  { id: 'schesir', name: 'Schesir', slug: 'schesir', logo_url: '/markalar/marca-logo-schesir.jpg' },
  { id: 'wanpy', name: 'Wanpy', slug: 'wanpy', logo_url: '/markalar/wanpy.png' },
  { id: 'exclusion', name: 'Exclusion', slug: 'exclusion', logo_url: '/markalar/exclusion.png' },
  { id: 'lavital', name: 'LaVital', slug: 'lavital', logo_url: '/markalar/Group_23071.webp' },
  { id: 'purelife', name: 'PureLife', slug: 'purelife', logo_url: '/markalar/petcomfor.jpg' },
];

// ==================== KATEGORİLER ====================
export const CATEGORY_DATA: Category[] = [
  // Ana Kategoriler
  { id: 'kedi', name: 'Kedi', slug: 'kedi', parent_id: null },
  { id: 'kopek', name: 'Köpek', slug: 'kopek', parent_id: null },
  { id: 'kus', name: 'Kuş', slug: 'kus', parent_id: null },
  { id: 'balik', name: 'Balık', slug: 'balik', parent_id: null },
  { id: 'kemirgen', name: 'Kemirgen', slug: 'kemirgen', parent_id: null },

  // Kedi Alt Kategorileri
  { id: 'kedi-mamasi', name: 'Kedi Mamaları', slug: 'kedi-mamasi', parent_id: 'kedi' },
  { id: 'kedi-kumu', name: 'Kedi Kumu', slug: 'kedi-kumu', parent_id: 'kedi' },
  { id: 'kedi-oyuncak', name: 'Kedi Oyuncakları', slug: 'kedi-oyuncak', parent_id: 'kedi' },
  { id: 'kedi-bakim', name: 'Kedi Bakım Ürünleri', slug: 'kedi-bakim', parent_id: 'kedi' },
  { id: 'kedi-tirmalama', name: 'Kedi Tırmalama Ürünleri', slug: 'kedi-tirmalama', parent_id: 'kedi' },
  { id: 'kedi-saglik', name: 'Kedi Sağlık Ürünleri', slug: 'kedi-saglik', parent_id: 'kedi' },
  { id: 'kedi-mama-kap', name: 'Kedi Mama ve Su Kapları', slug: 'kedi-mama-kap', parent_id: 'kedi' },
  { id: 'kedi-odul', name: 'Kedi Ödülleri', slug: 'kedi-odul', parent_id: 'kedi' },
  { id: 'kedi-tuvalet', name: 'Kedi Tuvalet Kabı ve Aksesuarları', slug: 'kedi-tuvalet', parent_id: 'kedi' },
  { id: 'kedi-vitamin', name: 'Kedi Vitaminleri', slug: 'kedi-vitamin', parent_id: 'kedi' },
  { id: 'kedi-tasma', name: 'Kedi Tasmaları', slug: 'kedi-tasma', parent_id: 'kedi' },
  { id: 'kedi-tasima', name: 'Kedi Taşıma ve Seyahat Ürünleri', slug: 'kedi-tasima', parent_id: 'kedi' },
  { id: 'kedi-hijyen', name: 'Kedi Hijyen ve Bakım Ürünleri', slug: 'kedi-hijyen', parent_id: 'kedi' },
  { id: 'kedi-yatak', name: 'Kedi Yatakları', slug: 'kedi-yatak', parent_id: 'kedi' },

  // Köpek Alt Kategorileri
  { id: 'kopek-mamasi', name: 'Köpek Mamaları', slug: 'kopek-mamasi', parent_id: 'kopek' },
  { id: 'kopek-oyuncak', name: 'Köpek Oyuncakları', slug: 'kopek-oyuncak', parent_id: 'kopek' },
  { id: 'kopek-bakim', name: 'Köpek Bakım Ürünleri', slug: 'kopek-bakim', parent_id: 'kopek' },
  { id: 'kopek-tasma', name: 'Köpek Tasma ve Kayışları', slug: 'kopek-tasma', parent_id: 'kopek' },
  { id: 'kopek-yatak', name: 'Köpek Yatakları ve Kulübeleri', slug: 'kopek-yatak', parent_id: 'kopek' },
  { id: 'kopek-mama-kap', name: 'Köpek Mama ve Su Kapları', slug: 'kopek-mama-kap', parent_id: 'kopek' },
  { id: 'kopek-odul', name: 'Köpek Ödülleri', slug: 'kopek-odul', parent_id: 'kopek' },
  { id: 'kopek-saglik', name: 'Köpek Sağlık Ürünleri', slug: 'kopek-saglik', parent_id: 'kopek' },
  { id: 'kopek-vitamin', name: 'Köpek Vitaminleri', slug: 'kopek-vitamin', parent_id: 'kopek' },
  { id: 'kopek-tasima', name: 'Köpek Taşıma Ürünleri', slug: 'kopek-tasima', parent_id: 'kopek' },
  { id: 'kopek-giyim', name: 'Köpek Giyim', slug: 'kopek-giyim', parent_id: 'kopek' },

  // Kuş Alt Kategorileri
  { id: 'kus-yemi', name: 'Kuş Yemleri', slug: 'kus-yemi', parent_id: 'kus' },
  { id: 'kus-kafes', name: 'Kuş Kafesleri', slug: 'kus-kafes', parent_id: 'kus' },
  { id: 'kus-aksesuar', name: 'Kuş Aksesuarları', slug: 'kus-aksesuar', parent_id: 'kus' },

  // Balık Alt Kategorileri
  { id: 'balik-yemi', name: 'Balık Yemleri', slug: 'balik-yemi', parent_id: 'balik' },
  { id: 'akvaryum', name: 'Akvaryum Ürünleri', slug: 'akvaryum', parent_id: 'balik' },

  // Kemirgen Alt Kategorileri
  { id: 'kemirgen-yemi', name: 'Kemirgen Yemleri', slug: 'kemirgen-yemi', parent_id: 'kemirgen' },
  { id: 'kemirgen-kafes', name: 'Kemirgen Kafesleri', slug: 'kemirgen-kafes', parent_id: 'kemirgen' },
];

// ==================== NAVİGASYON ====================
export const NAV_DATA = [
  {
    id: 'kedi',
    name: 'KEDİ DÜNYASI',
    slug: 'kedi',
    items: [
      {
        name: 'KEDİ MAMALARI',
        slug: 'kedi-mamasi',
        sub: [
          { name: 'Yavru Kedi Maması', image: '/menu_images/menu_kitten_food_1767813788837.png' },
          { name: 'Kısırlaştırılmış Kedi Maması', image: '/menu_images/menu_sterilized_cat_food_1767813803082.png' },
          { name: 'Tahılsız Kedi Maması', image: '/menu_images/menu_grain_free_cat_food_1767813819249.png' },
          { name: 'Yaş Mama', image: '/menu_images/menu_wet_cat_food_1767813846430.png' },
          { name: 'Kedi Ödülleri', image: '/menu_images/menu_cat_treats_1767813860288.png' }
        ]
      },
      {
        name: 'KEDİ KUMU & HİJYEN',
        slug: 'kedi-kumu',
        sub: [
          { name: 'Topaklanan Kum', image: '/menu_images/menu_clumping_litter_1767813876271.png' },
          { name: 'Silika Kristal Kum', image: '/menu_images/menu_silica_litter_1767813906301.png' },
          { name: 'Doğal Kedi Kumu', image: '/menu_images/menu_natural_litter_1767813921213.png' },
          { name: 'Tuvalet Kabı', image: '/menu_images/menu_litter_box_1767813936009.png' },
          { name: 'Hijyen Ürünleri', image: '/menu_images/menu_hygiene_products_1767813964699.png' }
        ]
      },
      {
        name: 'AKSESUAR & OYUNCAK',
        slug: 'kedi-oyuncak',
        sub: [
          { name: 'Kedi Tırmalama', image: '/menu_images/menu_scratching_post_1767813980194.png' },
          { name: 'Kedi Yatakları', image: '/menu_images/menu_cat_bed_1767813993596.png' },
          { name: 'Taşıma Çantası', image: '/menu_images/menu_carrier_bag_1767814022868.png' },
          { name: 'Kedi Oyuncakları', image: '/menu_images/menu_cat_toys_1767814037624.png' },
          { name: 'Mama ve Su Kapları', image: '/menu_images/menu_food_bowls_1767814051605.png' },
          { name: 'Kedi Tasmaları', image: '/menu_images/menu_cat_collar_1767814084204.png' }
        ]
      }
    ]
  },
  {
    id: 'kopek',
    name: 'KÖPEK DÜNYASI',
    slug: 'kopek',
    items: [
      {
        name: 'KÖPEK MAMALARI',
        slug: 'kopek-mamasi',
        sub: [
          { name: 'Yavru Köpek Maması', image: '/menu_images/menu_puppy_food_1767814099784.png' },
          { name: 'Yetişkin Köpek Maması', image: '/menu_images/menu_adult_dog_food_1767814113679.png' },
          { name: 'Tahılsız Mama', image: '/menu_images/menu_grain_free_cat_food_1767813819249.png' },
          { name: 'Konserve Mama', image: '/menu_images/menu_wet_cat_food_1767813846430.png' },
          { name: 'Köpek Ödülleri', image: '/menu_images/menu_cat_treats_1767813860288.png' }
        ]
      },
      {
        name: 'TASMA & GEZİNTİ',
        slug: 'kopek-tasma',
        sub: [
          { name: 'Köpek Tasmaları', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (1).jpg' },
          { name: 'Köpek Kayışları', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (2).jpg' },
          { name: 'Göğüs Tasması', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (3).jpg' },
          { name: 'Ağızlık', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (4).jpg' }
        ]
      },
      {
        name: 'YAŞAM ALANI',
        slug: 'kopek-yatak',
        sub: [
          { name: 'Köpek Yatakları', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (6).jpg' },
          { name: 'Köpek Kulübeleri', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (7).jpg' },
          { name: 'Köpek Oyuncakları', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (8).jpg' },
          { name: 'Mama ve Su Kapları', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (9).jpg' },
          { name: 'Köpek Giyim', image: '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (10).jpg' }
        ]
      }
    ]
  },
  {
    id: 'kus',
    name: 'KUŞ DÜNYASI',
    slug: 'kus',
    items: [
      {
        name: 'KUŞ YEMLERİ',
        slug: 'kus-yemi',
        sub: [
          { name: 'Muhabbet Kuşu Yemi', image: '/bird_images/budgie_food.png' },
          { name: 'Kanarya Yemi', image: '/bird_images/canary_food.png' },
          { name: 'Papağan Yemi', image: '/bird_images/parrot_food.jpg' },
          { name: 'Sultan Papağanı Yemi', image: '/bird_images/cockatiel_food.png' }
        ]
      },
      {
        name: 'KAFES & AKSESUAR',
        slug: 'kus-kafes',
        sub: [
          { name: 'Kuş Kafesleri', image: '/bird_images/bird_cage.png' },
          { name: 'Kuş Salıncagı', image: '/bird_images/bird_toys.png' },
          { name: 'Yem ve Su Kapları', image: '/bird_images/bird_feeder.png' },
          { name: 'Kuş Oyuncakları', image: '/bird_images/bird_toys.png' }
        ]
      }
    ]
  },
  {
    id: 'balik',
    name: 'BALIK & AKVARYUM',
    slug: 'balik',
    items: [
      {
        name: 'BALIK YEMLERİ',
        slug: 'balik-yemi',
        sub: [
          { name: 'Tropikal Balık Yemi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (38).jpg' },
          { name: 'Japon Balığı Yemi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (39).jpg' },
          { name: 'Cichlid Yemi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (40).jpg' },
          { name: 'Tablet Yem', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (41).jpg' }
        ]
      },
      {
        name: 'AKVARYUM ÜRÜNLERİ',
        slug: 'akvaryum',
        sub: [
          { name: 'Akvaryum Tankları', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (42).jpg' },
          { name: 'Filtre Sistemleri', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (43).jpg' },
          { name: 'Akvaryum Bitkileri', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (44).jpg' },
          { name: 'Dekorasyon', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (45).jpg' }
        ]
      }
    ]
  },
  {
    id: 'kemirgen',
    name: 'KEMİRGEN DÜNYASI',
    slug: 'kemirgen',
    items: [
      {
        name: 'HAMSTER ÜRÜNLERİ',
        slug: 'kemirgen-yemi',
        sub: [
          { name: 'Hamster Yemi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (46).jpg' },
          { name: 'Hamster Kafesi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (47).jpg' },
          { name: 'Hamster Çarkı', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (48).jpg' },
          { name: 'Hamster Yuvası', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (49).jpg' }
        ]
      },
      {
        name: 'TAVŞAN ÜRÜNLERİ',
        slug: 'kemirgen-kafes',
        sub: [
          { name: 'Tavşan Yemi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (50).jpg' },
          { name: 'Tavşan Kafesi', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (51).jpg' },
          { name: 'Saman ve Ot', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (52).jpg' },
          { name: 'Kemirgen Aksesuarları', image: '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (53).jpg' }
        ]
      }
    ]
  }
];

// ==================== ÜRÜNLER ====================
export const PRODUCTS: Product[] = [
  // ===== KEDİ MAMALARI =====
  {
    id: 'p1',
    name: 'Royal Canin Mother & Babycat Yavru Kedi Maması 2kg',
    slug: 'royal-canin-mother-babycat-2kg',
    description: 'Anne ve yavru kediler için özel formül. Bağışıklık sistemini destekler, kolay sindirilebilir yapısıyla hassas midelere uygundur.',
    price: 945.00,
    discounted_price: 850.00,
    stock: 25,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (1).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (2).jpg'],
    tags: ['Yavru', 'Premium', 'Bağışıklık'],
    is_active: true,
    rating: 4.9,
    review_count: 512,
    features: ['Yüksek Protein', 'Kolay Sindirim', 'DHA Destekli']
  },
  {
    id: 'p2',
    name: 'Royal Canin Indoor Ev Kedisi Maması 4kg',
    slug: 'royal-canin-indoor-4kg',
    description: 'Ev içinde yaşayan kediler için özel formül. Kilo kontrolü sağlar, tüy yumağı oluşumunu azaltır.',
    price: 1250.00,
    discounted_price: 1099.00,
    stock: 30,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (3).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (4).jpg'],
    tags: ['Indoor', 'Kilo Kontrolü'],
    is_active: true,
    rating: 4.8,
    review_count: 328,
    features: ['Düşük Kalori', 'Tüy Yumağı Kontrolü', 'L-Karnitin']
  },
  {
    id: 'p3',
    name: "Hill's Science Plan Kısırlaştırılmış Kedi Maması 3kg",
    slug: 'hills-sterile-cat-3kg',
    description: 'Kısırlaştırılmış kediler için bilimsel formül. Kilo kontrolü ve idrar yolu sağlığını destekler.',
    price: 1150.00,
    discounted_price: 990.00,
    stock: 45,
    brand_id: 'hills',
    brand_name: "Hill's",
    brand_logo_url: '/marka_fotograflari/Hill_s/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (5).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (6).jpg'],
    tags: ['Kısırlaştırılmış', 'Kilo Kontrolü'],
    is_active: true,
    rating: 4.9,
    review_count: 840,
    features: ['L-Karnitin', 'Dengeli Mineral', 'Omega 3-6']
  },
  {
    id: 'p4',
    name: 'N&D Prime Tavuklu Narlı Tahılsız Kedi Maması 1.5kg',
    slug: 'nd-prime-tavuk-nar-1-5kg',
    description: 'Doğal nar özleri ve serbest gezen tavuk etiyle hazırlanan tahılsız premium mama.',
    price: 780.00,
    discounted_price: 699.00,
    stock: 24,
    brand_id: 'nd',
    brand_name: 'N&D Farmina',
    brand_logo_url: '/marka_fotograflari/Farmina/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (7).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (8).jpg'],
    tags: ['Tahılsız', 'Premium'],
    is_active: true,
    rating: 4.8,
    review_count: 320,
    features: ['Tahılsız', 'Nar Özlü', 'Taze Et']
  },
  {
    id: 'p5',
    name: 'Acana Wild Prairie Tahılsız Kedi Maması 1.8kg',
    slug: 'acana-wild-prairie-1-8kg',
    description: 'Biyolojik olarak uygun, çoklu protein kaynaklı tahılsız mama. Tavuk, hindi ve yumurta içerir.',
    price: 1450.00,
    discounted_price: 1299.00,
    stock: 18,
    brand_id: 'acana',
    brand_name: 'Acana',
    brand_logo_url: '/marka_fotograflari/Acana/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (9).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (10).jpg'],
    tags: ['Tahılsız', 'Premium', 'Çoklu Protein'],
    is_active: true,
    rating: 5.0,
    review_count: 156,
    features: ['%70 Et', 'Kanada Üretim', 'WholePrey']
  },
  {
    id: 'p6',
    name: 'Pro Plan Sterilised Somonlu Kısır Kedi Maması 3kg',
    slug: 'proplan-sterilised-somon-3kg',
    description: 'OptiRenal formülü ile böbrek sağlığını destekler. Kısırlaştırılmış kediler için ideal.',
    price: 980.00,
    discounted_price: 879.00,
    stock: 35,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (11).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (14).jpg'],
    tags: ['Kısırlaştırılmış', 'Somonlu'],
    is_active: true,
    rating: 4.7,
    review_count: 445,
    features: ['OptiRenal', 'Böbrek Sağlığı', 'Omega Yağ Asitleri']
  },
  {
    id: 'p7',
    name: 'Orijen Cat & Kitten Tahılsız Kedi Maması 1.8kg',
    slug: 'orijen-cat-kitten-1-8kg',
    description: 'Ödüllü tahılsız formül. %85 kümes hayvanları ve balık, %15 meyve ve sebze.',
    price: 1650.00,
    discounted_price: null,
    stock: 12,
    brand_id: 'orijen',
    brand_name: 'Orijen',
    brand_logo_url: '/marka_fotograflari/Orijen/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (16).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (19).jpg'],
    tags: ['Tahılsız', 'Super Premium'],
    is_active: true,
    rating: 5.0,
    review_count: 89,
    features: ['%85 Et', 'Fresh Regional', 'Biologically Appropriate']
  },
  {
    id: 'p8',
    name: 'Brit Care Sterilised Ördekli Kedi Maması 2kg',
    slug: 'brit-care-sterilised-ordek-2kg',
    description: 'Hipoalerjenik formül, hassas sindirim sistemi için ördek proteini.',
    price: 720.00,
    discounted_price: 649.00,
    stock: 40,
    brand_id: 'brit-care',
    brand_name: 'Brit Care',
    brand_logo_url: '/markalar/brit.png',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (20).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (21).jpg'],
    tags: ['Hipoalerjenik', 'Ördekli'],
    is_active: true,
    rating: 4.6,
    review_count: 267,
    features: ['Tek Protein', 'Patatesiz', 'Prebiyotik']
  },
  {
    id: 'p9',
    name: 'Reflex Plus Tavuklu Yetişkin Kedi Maması 1.5kg',
    slug: 'reflex-plus-tavuk-1-5kg',
    description: 'Dengeli beslenme için tavuk etli ekonomik formül. Parlak tüyler için omega yağları.',
    price: 289.00,
    discounted_price: 249.00,
    stock: 80,
    brand_id: 'reflex',
    brand_name: 'Reflex',
    brand_logo_url: '/markalar/Group_135141.webp',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (22).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (23).jpg'],
    tags: ['Ekonomik', 'Tavuklu'],
    is_active: true,
    rating: 4.3,
    review_count: 892,
    features: ['Ekonomik', 'Omega 3-6', 'Taurin']
  },
  {
    id: 'p10',
    name: 'Jungle Somonlu Yetişkin Kedi Maması 1.5kg',
    slug: 'jungle-somon-1-5kg',
    description: 'Somon balığı ile zenginleştirilmiş, parlak tüyler ve sağlıklı deri için.',
    price: 245.00,
    discounted_price: 219.00,
    stock: 65,
    brand_id: 'jungle',
    brand_name: 'Jungle',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kedi-mamasi',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (24).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (25).jpg'],
    tags: ['Ekonomik', 'Somonlu'],
    is_active: true,
    rating: 4.2,
    review_count: 654,
    features: ['Somon Yağı', 'Vitamin E', 'Çinko']
  },

  // ===== KEDİ KUMU =====
  {
    id: 'p11',
    name: 'Ever Clean Extra Strength Kokusuz Kedi Kumu 10L',
    slug: 'ever-clean-extra-strength-10l',
    description: 'Aktif karbon teknolojisi ile maksimum koku kontrolü. Topaklanan, toz kaldırmayan formül.',
    price: 640.00,
    discounted_price: 549.00,
    stock: 100,
    brand_id: 'ever-clean',
    brand_name: 'Ever Clean',
    brand_logo_url: '/markalar/ever-clean.webp',
    category_id: 'kedi-kumu',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (26).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (27).jpg'],
    tags: ['Kokusuz', 'Ekstra Güçlü'],
    is_active: true,
    rating: 5.0,
    review_count: 2100,
    features: ['Aktif Karbon', 'Sıfır Toz', '14 Gün Koku Kontrolü']
  },
  {
    id: 'p12',
    name: 'Ever Clean Lavanta Kokulu Kedi Kumu 6L',
    slug: 'ever-clean-lavanta-6l',
    description: 'Lavanta esansı ile ferahlatıcı koku. Üstün topaklanma özelliği.',
    price: 420.00,
    discounted_price: 379.00,
    stock: 75,
    brand_id: 'ever-clean',
    brand_name: 'Ever Clean',
    brand_logo_url: '/markalar/ever-clean.webp',
    category_id: 'kedi-kumu',
    images: ['/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (28).jpg', '/trendyol%20kedi%20mamas%C4%B1/1_org_zoom (29).jpg'],
    tags: ['Lavanta', 'Parfümlü'],
    is_active: true,
    rating: 4.8,
    review_count: 1456,
    features: ['Lavanta Özü', 'Hızlı Topaklanma', 'Kolay Temizlik']
  },

  // ===== KÖPEK MAMALARI =====
  {
    id: 'p13',
    name: 'Royal Canin Medium Adult Yetişkin Köpek Maması 4kg',
    slug: 'royal-canin-medium-adult-4kg',
    description: 'Orta ırk yetişkin köpekler için optimal beslenme. Sindirim sağlığı ve ideal kilo.',
    price: 890.00,
    discounted_price: 799.00,
    stock: 28,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/royal elite yetişkin köpek maması.webp', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (1).jpg'],
    tags: ['Orta Irk', 'Yetişkin'],
    is_active: true,
    rating: 4.8,
    review_count: 623,
    features: ['Sindirim Sağlığı', 'Omega Yağları', 'Şekil Koruma']
  },
  {
    id: 'p14',
    name: 'Pro Plan Medium Puppy Kuzulu Yavru Köpek Maması 3kg',
    slug: 'proplan-medium-puppy-kuzu-3kg',
    description: 'Yavru köpekler için OptiStart formülü. Beyin gelişimi ve güçlü bağışıklık.',
    price: 890.00,
    discounted_price: null,
    stock: 30,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/purelife puppy kuzulu yavru köpek maması.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (2).jpg'],
    tags: ['Yavru', 'Kuzulu'],
    is_active: true,
    rating: 4.7,
    review_count: 150,
    features: ['OptiStart', 'DHA', 'Kolostrum']
  },
  {
    id: 'p15',
    name: 'Acana Grass-Fed Lamb Tahılsız Köpek Maması 2kg',
    slug: 'acana-grassfed-lamb-2kg',
    description: 'Sadece otla beslenen kuzu eti. Tek protein kaynaklı, hassas mideler için.',
    price: 1350.00,
    discounted_price: 1200.00,
    stock: 12,
    brand_id: 'acana',
    brand_name: 'Acana',
    brand_logo_url: '/marka_fotograflari/Acana/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (3).jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (4).jpg'],
    tags: ['Tahılsız', 'Premium', 'Kuzulu'],
    is_active: true,
    rating: 5.0,
    review_count: 88,
    features: ['Tek Protein', 'Hassas Sindirim', 'Kanada Üretim']
  },
  {
    id: 'p16',
    name: "Hill's Science Plan Adult Tavuklu Köpek Maması 2.5kg",
    slug: 'hills-adult-tavuk-2-5kg',
    description: 'Yetişkin köpekler için bilimsel beslenme. Kas yapısı ve enerji dengesi.',
    price: 780.00,
    discounted_price: 699.00,
    stock: 22,
    brand_id: 'hills',
    brand_name: "Hill's",
    brand_logo_url: '/marka_fotograflari/Hill_s/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/Hill\'s Prescription Diet.webp', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (5).jpg'],
    tags: ['Yetişkin', 'Tavuklu'],
    is_active: true,
    rating: 4.7,
    review_count: 334,
    features: ['Yüksek Protein', 'Omega 6', 'Vitamin E']
  },
  {
    id: 'p17',
    name: 'N&D Quinoa Skin & Coat Somonlu Köpek Maması 2.5kg',
    slug: 'nd-quinoa-skin-coat-2-5kg',
    description: 'Deri ve tüy sağlığı için kinoa ve somon. Tahılsız fonksiyonel mama.',
    price: 1120.00,
    discounted_price: 999.00,
    stock: 16,
    brand_id: 'nd',
    brand_name: 'N&D Farmina',
    brand_logo_url: '/marka_fotograflari/Farmina/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (6).jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (7).jpg'],
    tags: ['Tahılsız', 'Deri Sağlığı'],
    is_active: true,
    rating: 4.9,
    review_count: 178,
    features: ['Kinoa', 'Zerdeçal', 'Omega 3']
  },
  {
    id: 'p18',
    name: 'Reflex Premium Kuzulu Pirinçli Köpek Maması 3kg',
    slug: 'reflex-premium-kuzu-pirinc-3kg',
    description: 'Kuzu eti ve pirinç ile dengeli beslenme. Tüm ırklar için uygundur.',
    price: 395.00,
    discounted_price: 349.00,
    stock: 55,
    brand_id: 'reflex',
    brand_name: 'Reflex',
    brand_logo_url: '/markalar/Group_135141.webp',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/reflex-premium-kuzulu-ve-pirincli-yetiskin-kopek-mamasi-yetiskin-kuru-kopek-mamasi-reflex-1329064-45-B.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (8).jpg'],
    tags: ['Ekonomik', 'Kuzulu'],
    is_active: true,
    rating: 4.4,
    review_count: 567,
    features: ['Kuzu & Pirinç', 'Omega Yağları', 'Vitamin Kompleksi']
  },
  {
    id: 'p19',
    name: 'Jungle Kuzu Etli Yetişkin Köpek Maması 2.5kg',
    slug: 'jungle-kuzu-yetiskin-2-5kg',
    description: 'Kuzu etiyle lezzetli ve besleyici. Tüm ırklar için uygun ekonomik seçenek.',
    price: 285.00,
    discounted_price: 249.00,
    stock: 70,
    brand_id: 'jungle',
    brand_name: 'Jungle',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/jungle-yetiskin-kopek-mamasi-kuzu-etli-275-kg-yetiskin-kopek-mamasi-jungle-29164-22-B.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (9).jpg'],
    tags: ['Ekonomik', 'Kuzulu'],
    is_active: true,
    rating: 4.1,
    review_count: 423,
    features: ['Kuzu Eti', 'Doğal Lezzet', 'Vitamin D']
  },
  {
    id: 'p20',
    name: 'Enjoy Tavuklu Yetişkin Köpek Maması 15kg',
    slug: 'enjoy-tavuk-yetiskin-15kg',
    description: 'Büyük paket ekonomisi. Tavuk proteini ile dengeli günlük beslenme.',
    price: 789.00,
    discounted_price: 699.00,
    stock: 25,
    brand_id: 'enjoy',
    brand_name: 'Enjoy',
    brand_logo_url: '/markalar/Group_135146.avif',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/enjoy-tavuklu-yetiskin-kopek-mamasi-15-72625-.webp', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (10).jpg'],
    tags: ['Ekonomik', 'Büyük Paket'],
    is_active: true,
    rating: 4.2,
    review_count: 312,
    features: ['15kg Ekonomik', 'Tavuk', 'Günlük Beslenme']
  },
  {
    id: 'p21',
    name: 'BestPet Kuzu Etli Yetişkin Köpek Maması 15kg',
    slug: 'bestpet-kuzu-15kg',
    description: 'Premium kuzu eti ile besleyici formül. Büyük ırk köpekler için idealdir.',
    price: 849.00,
    discounted_price: 749.00,
    stock: 20,
    brand_id: 'bestpet',
    brand_name: 'BestPet',
    brand_logo_url: '/markalar/Group_135148.webp',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/bestpet-lamb-kuzu-etli-yetiskin-kopek-mamasi-15-kg-kopek-kuru-mamalari-bestpet-90388-69-B.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (11).jpg'],
    tags: ['Büyük Paket', 'Kuzulu'],
    is_active: true,
    rating: 4.3,
    review_count: 289,
    features: ['Kuzu Eti', 'Eklem Sağlığı', 'Parlak Tüy']
  },
  {
    id: 'p22',
    name: 'Dogido Etli Yetişkin Köpek Maması 15kg',
    slug: 'dogido-etli-15kg',
    description: 'Karışık et aromalı, lezzetli ve ekonomik. Günlük enerji ihtiyacını karşılar.',
    price: 695.00,
    discounted_price: 599.00,
    stock: 35,
    brand_id: 'dogido',
    brand_name: 'Dogido',
    brand_logo_url: '/markalar/Group_135149.webp',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/dogido yetişken köpek maması.png', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (12).jpg'],
    tags: ['Ekonomik', 'Etli'],
    is_active: true,
    rating: 4.0,
    review_count: 567,
    features: ['Karışık Et', 'Enerji Dengesi', 'Vitamin Destekli']
  },
  {
    id: 'p23',
    name: 'ProLine Tavuklu Yetişkin Köpek Maması 3kg',
    slug: 'proline-tavuk-3kg',
    description: 'Tavuk proteini ile güçlü kaslar. Aktif köpekler için dengeli formül.',
    price: 329.00,
    discounted_price: 289.00,
    stock: 45,
    brand_id: 'proline',
    brand_name: 'ProLine',
    brand_logo_url: '/markalar/Group_135152.webp',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/proline yetişken köpek maması.png', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (13).jpg'],
    tags: ['Ekonomik', 'Tavuklu'],
    is_active: true,
    rating: 4.2,
    review_count: 234,
    features: ['Tavuk', 'Aktif Köpekler', 'Kas Yapısı']
  },
  {
    id: 'p24',
    name: 'Felicia Düşük Tahıllı Kuzulu Köpek Maması 3kg',
    slug: 'felicia-dusuk-tahil-kuzu-3kg',
    description: 'Düşük tahıl içerikli, hassas sindirim için kuzu eti ve pirinç.',
    price: 445.00,
    discounted_price: 399.00,
    stock: 38,
    brand_id: 'felicia',
    brand_name: 'Felicia',
    brand_logo_url: '/markalar/felicia.png',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/felicia-dusuk-tahilli-kuzulu-ve-pirincli-yetiskin-kopek-mamasi-3-kg-kopek-kuru-mamalari-felicia-98465-92-B.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (14).jpg'],
    tags: ['Düşük Tahıl', 'Kuzulu'],
    is_active: true,
    rating: 4.5,
    review_count: 178,
    features: ['Düşük Tahıl', 'Kuzu & Pirinç', 'Hassas Sindirim']
  },
  {
    id: 'p25',
    name: 'LaVital Büyük Irk Yavru Köpek Maması 3kg',
    slug: 'lavital-buyuk-irk-yavru-3kg',
    description: 'Büyük ırk yavru köpekler için özel formül. Eklem ve kemik sağlığı destekli.',
    price: 489.00,
    discounted_price: 439.00,
    stock: 25,
    brand_id: 'lavital',
    brand_name: 'LaVital',
    brand_logo_url: '/markalar/Group_23071.webp',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/lavital-buyuk-irk-yavru-kuru-kopek-mamasi-maxi-puppy-kuzu-etli-3kg-489-90-O.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (15).jpg'],
    tags: ['Yavru', 'Büyük Irk'],
    is_active: true,
    rating: 4.6,
    review_count: 123,
    features: ['Eklem Desteği', 'Kalsiyum', 'DHA']
  },
  {
    id: 'p26',
    name: 'PureLife Puppy Kuzulu Yavru Köpek Maması 3kg',
    slug: 'purelife-puppy-kuzu-3kg',
    description: 'Yavru köpekler için saf ve doğal kuzu eti. Büyüme dönemini destekler.',
    price: 520.00,
    discounted_price: 469.00,
    stock: 30,
    brand_id: 'purelife',
    brand_name: 'PureLife',
    brand_logo_url: '/markalar/petcomfor.jpg',
    category_id: 'kopek-mamasi',
    images: ['/K%C3%B6pek%20Mamas%C4%B1/purelife puppy kuzulu yavru köpek maması.jpg', '/trendyol%20k%C3%B6pek%20mamas%C4%B1/1_org_zoom (16).jpg'],
    tags: ['Yavru', 'Kuzulu'],
    is_active: true,
    rating: 4.5,
    review_count: 98,
    features: ['Saf Kuzu', 'Doğal', 'Büyüme Desteği']
  },
  // ===== YENİ KEDİ MAMALARI (kedi mamaları klasöründen) =====
  {
    id: 'p27',
    name: 'N&D Düşük Tahıllı Somonlu Kısırlaştırılmış Kedi Maması 10kg',
    slug: 'nd-dusuk-tahil-somon-10kg',
    description: 'Kısırlaştırılmış kediler için düşük tahıllı, somonlu premium mama. Kilo kontrolü ve parlak tüy yapısı sağlar.',
    price: 2850.00,
    discounted_price: 2499.00,
    stock: 15,
    brand_id: 'nd',
    brand_name: 'N&D Farmina',
    brand_logo_url: '/marka_fotograflari/Farmina/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_10_nd-dusuk-tahilli-somonlu-kisirlastirilmis-kedi-mamasi-10-kg-68764f31aad93.jpg'],
    tags: ['Kısırlaştırılmış', 'Düşük Tahıl', 'Somonlu', 'Premium'],
    is_active: true,
    rating: 4.9,
    review_count: 267,
    features: ['Düşük Tahıl', 'Omega 3-6', 'Somon Proteini']
  },
  {
    id: 'p28',
    name: 'Paw Paw Gurme Renkli Kedi Maması 15kg',
    slug: 'paw-paw-gurme-renkli-15kg',
    description: 'Renkli ve lezzetli granüllerle gurme beslenme deneyimi. Ekonomik büyük paket.',
    price: 1290.00,
    discounted_price: 1099.00,
    stock: 40,
    brand_id: 'jungle',
    brand_name: 'Paw Paw',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_11_paw-paw-gurme-renkli-kedi-mamasi-15-kg-66c325936ca7c.jpg'],
    tags: ['Ekonomik', 'Gurme', 'Büyük Paket'],
    is_active: true,
    rating: 4.3,
    review_count: 412,
    features: ['15kg Ekonomik', 'Renkli Granüller', 'Dengeli Beslenme']
  },
  {
    id: 'p29',
    name: 'Pro Plan Original Kitten Tavuklu Yavru Kedi Maması 10kg',
    slug: 'proplan-kitten-tavuk-10kg',
    description: 'Yavru kediler için bilimsel formül. Beyin gelişimi ve bağışıklık sistemi desteği.',
    price: 2450.00,
    discounted_price: 2199.00,
    stock: 18,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_12_pro-plan-original-kitten-tavuklu-ve-pirincli-yavru-kedi-mamasi-10-kg-66ba2e9deeeb4.jpg'],
    tags: ['Yavru', 'Premium', 'Tavuklu'],
    is_active: true,
    rating: 4.8,
    review_count: 356,
    features: ['DHA Beyin Gelişimi', 'Kolostrum', 'Yüksek Protein']
  },
  {
    id: 'p30',
    name: 'N&D Tropical Selection Tavuklu Kısır Yetişkin Kedi Maması 10kg',
    slug: 'nd-tropical-tavuk-kisir-10kg',
    description: 'Tropikal meyvelerle zenginleştirilmiş, kısırlaştırılmış kediler için özel formül.',
    price: 2750.00,
    discounted_price: 2399.00,
    stock: 12,
    brand_id: 'nd',
    brand_name: 'N&D Farmina',
    brand_logo_url: '/marka_fotograflari/Farmina/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_13_nd-tropical-selection-tavuklu-kisir-yetiskin-kedi-mamasi-10-kg-66c4d5064a7cb.jpg'],
    tags: ['Kısırlaştırılmış', 'Tropikal', 'Premium'],
    is_active: true,
    rating: 4.7,
    review_count: 189,
    features: ['Tropikal Meyve', 'Kilo Kontrolü', 'Parlak Tüy']
  },
  {
    id: 'p31',
    name: 'Pro Plan Kısırlaştırılmış Tavuk Hindi Kedi Maması 10.2kg',
    slug: 'proplan-kisir-tavuk-hindi-10kg',
    description: 'Kısırlaştırılmış kediler için tavuk ve hindi ile protein dengesi. Kilo yönetimi destekli.',
    price: 2650.00,
    discounted_price: 2299.00,
    stock: 22,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_14_pro-plan-kisirlastirilmis-tavukhindili-kedi-mamasi-102-kg-66d70df6f19e1.jpg'],
    tags: ['Kısırlaştırılmış', 'Premium'],
    is_active: true,
    rating: 4.8,
    review_count: 423,
    features: ['Tavuk & Hindi', 'Optirenal', 'Kilo Kontrolü']
  },
  {
    id: 'p32',
    name: 'N&D Düşük Tahıllı Tavuklu Narlı Kısır Kedi Maması 10kg',
    slug: 'nd-tavuk-nar-kisir-10kg',
    description: 'Tavuk ve nar kombinasyonu ile antioksidan destekli, kısırlaştırılmış kediler için ideal mama.',
    price: 2890.00,
    discounted_price: 2549.00,
    stock: 10,
    brand_id: 'nd',
    brand_name: 'N&D Farmina',
    brand_logo_url: '/marka_fotograflari/Farmina/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_15_nd-dusuk-tahilli-tavuklu-ve-narli-kisirlastirilmis-yetiskin-kedi-mamasi-10-kg-68cd3b94a2da2.jpg'],
    tags: ['Kısırlaştırılmış', 'Düşük Tahıl', 'Narlı'],
    is_active: true,
    rating: 4.9,
    review_count: 312,
    features: ['Nar Antioksidan', 'Düşük Tahıl', 'Premium Tavuk']
  },
  {
    id: 'p33',
    name: 'Goody Etli Yetişkin Kedi Maması 15kg',
    slug: 'goody-etli-yetiskin-15kg',
    description: 'Ekonomik ve lezzetli etli mama. Günlük beslenme ihtiyaçlarını karşılar.',
    price: 890.00,
    discounted_price: 749.00,
    stock: 55,
    brand_id: 'jungle',
    brand_name: 'Goody',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kedi-mamasi',
    images: ['/kedi%20mamalar%C4%B1/imgi_16_goody-etli-yetiskin-kedi-mamasi-15-kg-66c416d28c42f.jpg'],
    tags: ['Ekonomik', 'Etli', 'Büyük Paket'],
    is_active: true,
    rating: 4.2,
    review_count: 567,
    features: ['15kg Ekonomik', 'Et Proteini', 'Günlük Beslenme']
  },

  // ===== KUŞ ÜRÜNLERİ =====
  {
    id: 'p34',
    name: 'Nature Plan Papağan Yemi 800g x 5 Adet',
    slug: 'nature-plan-papagan-yemi-800g',
    description: 'Papağanlar için özel karışım yem. Vitamin ve mineral destekli, doğal içerikler.',
    price: 349.00,
    discounted_price: 299.00,
    stock: 35,
    brand_id: 'jungle',
    brand_name: 'Nature Plan',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kus-yemi',
    images: ['/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/imgi_10_nature-plan-papagan-yemi-800-g-x-5-adet-66c3b16044b4e.jpg'],
    tags: ['Kuş', 'Papağan', 'Yem'],
    is_active: true,
    rating: 4.6,
    review_count: 187,
    features: ['Vitamin Destekli', 'Doğal', '5 Adet Paket']
  },
  {
    id: 'p35',
    name: 'Garden Mix Platin Sarı Dal Darı 150gr',
    slug: 'garden-mix-sari-dal-dari-150gr',
    description: 'Muhabbet kuşları ve kanarya için dal darı. Doğal ve lezzetli ödül.',
    price: 45.00,
    discounted_price: 39.00,
    stock: 80,
    brand_id: 'jungle',
    brand_name: 'Garden Mix',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kus-yemi',
    images: ['/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/imgi_11_garden-mix-platin-sari-dal-dari-150gr-66c54835ecf60.jpg'],
    tags: ['Kuş', 'Ödül', 'Darı'],
    is_active: true,
    rating: 4.8,
    review_count: 342,
    features: ['Doğal', 'Dal Darı', 'Ödül Yem']
  },
  {
    id: 'p36',
    name: 'Gold Wings Premium Muhabbet Kuşu Yemi 1kg',
    slug: 'gold-wings-muhabbet-yemi-1kg',
    description: 'Premium kalite muhabbet kuşu yemi. Zengin vitamin ve mineral içeriği.',
    price: 89.00,
    discounted_price: 79.00,
    stock: 65,
    brand_id: 'jungle',
    brand_name: 'Gold Wings',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kus-yemi',
    images: ['/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/imgi_17_gold-wings-premium-muhabbet-kusu-yemi-1-kg-66c5482670e81.jpg'],
    tags: ['Kuş', 'Muhabbet', 'Premium'],
    is_active: true,
    rating: 4.7,
    review_count: 256,
    features: ['Premium', 'Vitamin Zengin', '1kg Paket']
  },
  {
    id: 'p37',
    name: 'Dayang Ayaklı Papağan Kafesi Siyah 45x45x156cm',
    slug: 'dayang-papagan-kafesi-siyah',
    description: 'Büyük papağanlar için geniş yaşam alanı. Ayaklı tasarım, kolay temizlik.',
    price: 2890.00,
    discounted_price: 2499.00,
    stock: 8,
    brand_id: 'jungle',
    brand_name: 'Dayang',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kus-kafes',
    images: ['/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/imgi_23_dayang-ayakli-papagan-kafesi-siyah-457x457x156-cm-66e821dd9431b.jpg'],
    tags: ['Kuş', 'Kafes', 'Papağan'],
    is_active: true,
    rating: 4.5,
    review_count: 89,
    features: ['Ayaklı', 'Geniş', 'Kolay Temizlik']
  },
  {
    id: 'p38',
    name: 'Miapet Kuşlar İçin Pleksi Ahşap Merdiven Oyuncak 30cm',
    slug: 'miapet-kus-merdiven-oyuncak-30cm',
    description: 'Kuşlar için eğlenceli merdiven oyuncak. Ahşap ve pleksi malzeme.',
    price: 79.00,
    discounted_price: 69.00,
    stock: 45,
    brand_id: 'jungle',
    brand_name: 'Miapet',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kus-aksesuar',
    images: ['/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/Kuş Ürünleri Ürünleri ve Fiyatları - idefix/imgi_15_miapet-kuslar-icin-pleksi-ahsap-oyuncak-merdiven-30-cm-66c0e86353a06.jpg'],
    tags: ['Kuş', 'Oyuncak', 'Aksesuar'],
    is_active: true,
    rating: 4.4,
    review_count: 123,
    features: ['Ahşap', 'Pleksi', 'Eğlenceli']
  },

  // ===== BALIK & AKVARYUM ÜRÜNLERİ =====
  {
    id: 'p39',
    name: 'Tetra Discus Granül Balık Yemi 10Lt 3kg',
    slug: 'tetra-discus-granul-10lt-3kg',
    description: 'Discus balıkları için özel granül yem. Renk parlaklığı ve sağlıklı gelişim.',
    price: 1850.00,
    discounted_price: 1599.00,
    stock: 12,
    brand_id: 'jungle',
    brand_name: 'Tetra',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'balik-yemi',
    images: ['/Balık Ürünleri ve Fiyatları - idefix/Balık Ürünleri ve Fiyatları - idefix/imgi_10_tetra-discus-granul-balik-yemi-10-lt-3-kg-66c54cfe8409c.jpg'],
    tags: ['Balık', 'Discus', 'Premium'],
    is_active: true,
    rating: 4.9,
    review_count: 156,
    features: ['Granül', 'Renk Parlaklığı', 'Premium']
  },
  {
    id: 'p40',
    name: 'Sobo HS-300 Akvaryum Cam Isıtıcı 300W',
    slug: 'sobo-akvaryum-isitici-300w',
    description: 'Akvaryum için güvenilir cam ısıtıcı. Ayarlanabilir sıcaklık kontrolü.',
    price: 289.00,
    discounted_price: 249.00,
    stock: 25,
    brand_id: 'jungle',
    brand_name: 'Sobo',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/Balık Ürünleri ve Fiyatları - idefix/Balık Ürünleri ve Fiyatları - idefix/imgi_11_sobo-hs-300-akvaryum-cam-isitici-300w-67333f5549907.jpg'],
    tags: ['Akvaryum', 'Isıtıcı', 'Ekipman'],
    is_active: true,
    rating: 4.6,
    review_count: 234,
    features: ['300W', 'Cam', 'Ayarlanabilir']
  },
  {
    id: 'p41',
    name: 'Sobo WP-3300 Akvaryum Kafa Motoru',
    slug: 'sobo-wp3300-kafa-motoru',
    description: 'Güçlü akvaryum filtre motoru. Sessiz çalışma, yüksek verimlilik.',
    price: 345.00,
    discounted_price: 299.00,
    stock: 18,
    brand_id: 'jungle',
    brand_name: 'Sobo',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/Balık Ürünleri ve Fiyatları - idefix/Balık Ürünleri ve Fiyatları - idefix/imgi_12_sobo-wp-3300-kafa-motoru-66c5314d9b734.jpg'],
    tags: ['Akvaryum', 'Filtre', 'Motor'],
    is_active: true,
    rating: 4.5,
    review_count: 178,
    features: ['Güçlü', 'Sessiz', 'Verimli']
  },
  {
    id: 'p42',
    name: 'Kanki Pet Mini Akvaryum Mor Sehpa 30cm',
    slug: 'kanki-mini-akvaryum-mor-30cm',
    description: 'Dekoratif mini akvaryum seti. Renkli kapak ve şık tasarım.',
    price: 459.00,
    discounted_price: 399.00,
    stock: 15,
    brand_id: 'jungle',
    brand_name: 'Kanki Pet',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/Balık Ürünleri ve Fiyatları - idefix/Balık Ürünleri ve Fiyatları - idefix/imgi_13_kanki-pet-kp3018-mini-akvaryum-mor-sehpa-30-cm-66d83e050e043.jpg'],
    tags: ['Akvaryum', 'Mini', 'Dekoratif'],
    is_active: true,
    rating: 4.3,
    review_count: 98,
    features: ['Mini', 'Sehpalı', 'Dekoratif']
  },

  // ===== HAMSTER ÜRÜNLERİ =====
  {
    id: 'p43',
    name: 'Vitakraft Menu Premium Hamster Yemi 1000gr',
    slug: 'vitakraft-hamster-yemi-1000gr',
    description: 'Premium kalite hamster yemi. Dengeli beslenme, vitamin destekli.',
    price: 189.00,
    discounted_price: 169.00,
    stock: 40,
    brand_id: 'jungle',
    brand_name: 'Vitakraft',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-yemi',
    images: ['/Hamster Ürünleri ve Fiyatları - idefix/Hamster Ürünleri ve Fiyatları - idefix/imgi_5_vitakraft-menu-premium-hamster-yemi-1000-gr-66c548dd7c94b.jpg'],
    tags: ['Hamster', 'Yem', 'Premium'],
    is_active: true,
    rating: 4.7,
    review_count: 289,
    features: ['Premium', 'Vitamin Destekli', '1kg']
  },
  {
    id: 'p44',
    name: 'Garden Mix Kemirgenler İçin Kuru Yonca',
    slug: 'garden-mix-kemirgen-kuru-yonca',
    description: 'Hamster ve kemirgenler için doğal kuru yonca. Lif kaynağı.',
    price: 65.00,
    discounted_price: 55.00,
    stock: 60,
    brand_id: 'jungle',
    brand_name: 'Garden Mix',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-yemi',
    images: ['/Hamster Ürünleri ve Fiyatları - idefix/Hamster Ürünleri ve Fiyatları - idefix/imgi_10_garden-mix-kemirgenler-icin-kuru-yonca-66e8f8f13784e.jpg'],
    tags: ['Hamster', 'Yonca', 'Doğal'],
    is_active: true,
    rating: 4.5,
    review_count: 167,
    features: ['Doğal', 'Lif Kaynağı', 'Sağlıklı']
  },
  {
    id: 'p45',
    name: 'Eurogold QH-40711 Hamster Kafesi 34x23x29cm',
    slug: 'eurogold-hamster-kafesi-40711',
    description: 'Kompakt hamster kafesi. Çark ve aksesuar dahil.',
    price: 459.00,
    discounted_price: 399.00,
    stock: 22,
    brand_id: 'jungle',
    brand_name: 'Eurogold',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-kafes',
    images: ['/Hamster Ürünleri ve Fiyatları - idefix/Hamster Ürünleri ve Fiyatları - idefix/imgi_12_eurogold-qh-40711-hamster-kafesi-34x23x29-olculerinde-66c3b1980681c.jpg'],
    tags: ['Hamster', 'Kafes'],
    is_active: true,
    rating: 4.4,
    review_count: 145,
    features: ['Çark Dahil', 'Kompakt', 'Kolay Temizlik']
  },
  {
    id: 'p46',
    name: 'Dayang Aksesuarlı Hamster Kafesi Renkli 35x26x23cm',
    slug: 'dayang-aksesuarli-hamster-kafesi',
    description: 'Renkli ve eğlenceli hamster kafesi. Tüm aksesuarlar dahil.',
    price: 529.00,
    discounted_price: 459.00,
    stock: 18,
    brand_id: 'jungle',
    brand_name: 'Dayang',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-kafes',
    images: ['/Hamster Ürünleri ve Fiyatları - idefix/Hamster Ürünleri ve Fiyatları - idefix/imgi_15_dayang-aksesuarli-hamster-kafesi-renkli-35x26x23-cm-677d14c7a9516.jpg'],
    tags: ['Hamster', 'Kafes', 'Aksesuarlı'],
    is_active: true,
    rating: 4.6,
    review_count: 112,
    features: ['Aksesuarlı', 'Renkli', 'Eğlenceli']
  },
  {
    id: 'p47',
    name: 'Hamster Banyosu Kumu Sinsilla 6kg 20Lt',
    slug: 'hamster-banyo-kumu-6kg',
    description: 'Hamster ve kemirgenler için özel banyo kumu. Hijyenik ve doğal.',
    price: 189.00,
    discounted_price: 165.00,
    stock: 35,
    brand_id: 'jungle',
    brand_name: 'Generic',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-yemi',
    images: ['/Hamster Ürünleri ve Fiyatları - idefix/Hamster Ürünleri ve Fiyatları - idefix/imgi_6_hamster-banyosu-kumu-sinsilla-gerbils-chinchilla-fare-degus-icin-banyo-veya-lazimlik-kumu-6-kg-20-lt-68cccbe8a2c40.jpg'],
    tags: ['Hamster', 'Banyo Kumu', 'Hijyen'],
    is_active: true,
    rating: 4.3,
    review_count: 98,
    features: ['6kg', 'Hijyenik', 'Doğal']
  },

  // ===== TAVŞAN ÜRÜNLERİ =====
  {
    id: 'p48',
    name: 'Vitakraft Menu Rabbit Tavşan Yemi 1000gr',
    slug: 'vitakraft-tavsan-yemi-1000gr',
    description: 'Premium tavşan yemi. Dengeli vitamin ve mineral içeriği.',
    price: 195.00,
    discounted_price: 175.00,
    stock: 38,
    brand_id: 'jungle',
    brand_name: 'Vitakraft',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-yemi',
    images: ['/Tavşan Ürünleri ve Fiyatları - idefix/Tavşan Ürünleri ve Fiyatları - idefix/imgi_10_vitakraft-menu-rabbit-tavsan-yemi-1000-gr-66c548dd60f37.jpg'],
    tags: ['Tavşan', 'Yem', 'Premium'],
    is_active: true,
    rating: 4.8,
    review_count: 234,
    features: ['Premium', 'Vitamin Zengin', '1kg']
  },
  {
    id: 'p49',
    name: 'Orijin Tavşan Kafesi 45x32x31cm',
    slug: 'orijin-tavsan-kafesi-45x32x31',
    description: 'Geniş tavşan kafesi. Rahat yaşam alanı ve kolay erişim.',
    price: 689.00,
    discounted_price: 599.00,
    stock: 14,
    brand_id: 'jungle',
    brand_name: 'Orijin',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-kafes',
    images: ['/Tavşan Ürünleri ve Fiyatları - idefix/Tavşan Ürünleri ve Fiyatları - idefix/imgi_11_orijin-tavsan-kafesi-45x32x31-cm-66c548e8a467f.jpg'],
    tags: ['Tavşan', 'Kafes'],
    is_active: true,
    rating: 4.5,
    review_count: 89,
    features: ['Geniş', 'Kolay Erişim', 'Dayanıklı']
  },
  {
    id: 'p50',
    name: 'Mandu Ahşap Tavşan Evi Büyük Boy',
    slug: 'mandu-ahsap-tavsan-evi-buyuk',
    description: 'Doğal ahşap tavşan evi. Sıcak ve rahat yaşam alanı.',
    price: 459.00,
    discounted_price: 399.00,
    stock: 20,
    brand_id: 'jungle',
    brand_name: 'Mandu',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-kafes',
    images: ['/Tavşan Ürünleri ve Fiyatları - idefix/Tavşan Ürünleri ve Fiyatları - idefix/imgi_15_mandu-ahsap-tavsan-evi-buyuk-boy-66ba23ec4fffe.jpg'],
    tags: ['Tavşan', 'Ev', 'Ahşap'],
    is_active: true,
    rating: 4.7,
    review_count: 156,
    features: ['Ahşap', 'Büyük Boy', 'Doğal']
  },
  {
    id: 'p51',
    name: 'Quik Kuru Yonca Kemirgen Otu 350gr',
    slug: 'quik-kuru-yonca-kemirgen-350gr',
    description: 'Tavşan ve kemirgenler için kuru yonca. Lif ve vitamin kaynağı.',
    price: 55.00,
    discounted_price: 45.00,
    stock: 75,
    brand_id: 'jungle',
    brand_name: 'Quik',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-yemi',
    images: ['/Tavşan Ürünleri ve Fiyatları - idefix/Tavşan Ürünleri ve Fiyatları - idefix/imgi_12_quik-kuru-yonca-kemirgen-otu-350-gr-167-66bbc7de54225.jpg'],
    tags: ['Tavşan', 'Yonca', 'Doğal'],
    is_active: true,
    rating: 4.4,
    review_count: 198,
    features: ['Kuru Yonca', 'Lif Kaynağı', '350gr']
  },
  {
    id: 'p52',
    name: 'Zampa Pedro Tavşan ve Guinea Pig Kafesi 69x44.5x35.5cm',
    slug: 'zampa-pedro-tavsan-kafesi',
    description: 'Geniş tavşan ve guinea pig kafesi. Premium kalite, dayanıklı yapı.',
    price: 1290.00,
    discounted_price: 1099.00,
    stock: 10,
    brand_id: 'jungle',
    brand_name: 'Zampa',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'kemirgen-kafes',
    images: ['/Tavşan Ürünleri ve Fiyatları - idefix/Tavşan Ürünleri ve Fiyatları - idefix/imgi_25_zampa-pedro-tavsan-ve-guinea-pig-kafesi-69x445x355-cm-693a40c74a249.png'],
    tags: ['Tavşan', 'Guinea Pig', 'Kafes'],
    is_active: true,
    rating: 4.6,
    review_count: 67,
    features: ['Geniş', 'Premium', 'Dayanıklı']
  },

  // ===== YENİ KÖPEK ÜRÜNLERİ (işlenmiş görseller) =====
  {
    id: 'p53',
    name: 'Royal Canin Cavalier King Charles Adult 1.5kg',
    slug: 'royal-canin-cavalier-adult-1-5kg',
    description: 'Cavalier King Charles ırkı için özel formül. Kalp sağlığını destekler, parlak tüyler için omega yağları içerir.',
    price: 845.00,
    discounted_price: 749.00,
    stock: 22,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_001.jpg', '/products/kopek/mama/kopek_mama_002.jpg'],
    tags: ['Özel Irk', 'Premium', 'Cavalier'],
    is_active: true,
    rating: 4.9,
    review_count: 187,
    features: ['Kalp Sağlığı', 'Parlak Tüy', 'Özel Irk']
  },
  {
    id: 'p54',
    name: 'Royal Canin Chihuahua Adult 1.5kg',
    slug: 'royal-canin-chihuahua-adult-1-5kg',
    description: 'Chihuahua ırkı için özel granül boyutu. Küçük çeneler için ideal, yüksek enerji formülü.',
    price: 795.00,
    discounted_price: 699.00,
    stock: 28,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_003.jpg', '/products/kopek/mama/kopek_mama_004.jpg'],
    tags: ['Özel Irk', 'Premium', 'Chihuahua'],
    is_active: true,
    rating: 4.8,
    review_count: 234,
    features: ['Mini Granül', 'Yüksek Enerji', 'Özel Irk']
  },
  {
    id: 'p55',
    name: 'Royal Canin Pug Adult 1.5kg',
    slug: 'royal-canin-pug-adult-1-5kg',
    description: 'Pug ırkı için kilo kontrolü formülü. Solunum ve sindirim sağlığını destekler.',
    price: 825.00,
    discounted_price: 729.00,
    stock: 20,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_005.jpg', '/products/kopek/mama/kopek_mama_006.jpg'],
    tags: ['Özel Irk', 'Premium', 'Pug'],
    is_active: true,
    rating: 4.7,
    review_count: 198,
    features: ['Kilo Kontrolü', 'Solunum Desteği', 'Özel Irk']
  },
  {
    id: 'p56',
    name: 'Royal Canin Shih Tzu Adult 1.5kg',
    slug: 'royal-canin-shih-tzu-adult-1-5kg',
    description: 'Shih Tzu ırkı için tüy bakımı formülü. Uzun tüyler için özel besinler.',
    price: 815.00,
    discounted_price: 719.00,
    stock: 24,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_007.jpg', '/products/kopek/mama/kopek_mama_008.jpg'],
    tags: ['Özel Irk', 'Premium', 'Shih Tzu'],
    is_active: true,
    rating: 4.9,
    review_count: 156,
    features: ['Tüy Bakımı', 'Omega Yağları', 'Özel Irk']
  },
  {
    id: 'p57',
    name: 'Royal Canin Yorkshire Terrier Adult 1.5kg',
    slug: 'royal-canin-yorkshire-adult-1-5kg',
    description: 'Yorkshire Terrier için ipeksi tüy formülü. Biyotin ve EPA-DHA destekli.',
    price: 835.00,
    discounted_price: 739.00,
    stock: 26,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_009.jpg', '/products/kopek/mama/kopek_mama_010.jpg'],
    tags: ['Özel Irk', 'Premium', 'Yorkshire'],
    is_active: true,
    rating: 4.8,
    review_count: 289,
    features: ['İpeksi Tüy', 'Biyotin', 'Özel Irk']
  },
  {
    id: 'p58',
    name: 'Acana Small Breed Tahılsız Mama 1.8kg',
    slug: 'acana-small-breed-1-8kg',
    description: 'Küçük ırk köpekler için biyolojik olarak uygun, tahılsız formül.',
    price: 1390.00,
    discounted_price: 1249.00,
    stock: 15,
    brand_id: 'acana',
    brand_name: 'Acana',
    brand_logo_url: '/marka_fotograflari/Acana/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_011.jpg', '/products/kopek/mama/kopek_mama_012.jpg'],
    tags: ['Tahılsız', 'Premium', 'Küçük Irk'],
    is_active: true,
    rating: 5.0,
    review_count: 134,
    features: ['%70 Et', 'Tahılsız', 'Biyolojik']
  },
  {
    id: 'p59',
    name: 'Wanpy Tavuklu Köpek Ödül Bisküvisi 100gr',
    slug: 'wanpy-tavuk-biskuvi-100gr',
    description: 'Gerçek tavuk etiyle hazırlanan lezzetli ödül bisküvisi. Eğitim için ideal.',
    price: 89.00,
    discounted_price: 75.00,
    stock: 85,
    brand_id: 'wanpy',
    brand_name: 'Wanpy',
    brand_logo_url: '/markalar/wanpy.png',
    category_id: 'kopek-odul',
    images: ['/products/kopek/mama/kopek_mama_019.jpg', '/products/kopek/mama/kopek_mama_020.jpg'],
    tags: ['Ödül', 'Tavuklu', 'Eğitim'],
    is_active: true,
    rating: 4.7,
    review_count: 456,
    features: ['Gerçek Tavuk', 'Eğitim', 'Lezzetli']
  },
  {
    id: 'p60',
    name: 'Schesir Jölede Tavuk Fileto Köpek Konservesi 150gr',
    slug: 'schesir-jole-tavuk-150gr',
    description: 'Doğal jöle içinde lezzetli tavuk filetosu. Katkısız, saf protein.',
    price: 69.00,
    discounted_price: 59.00,
    stock: 60,
    brand_id: 'schesir',
    brand_name: 'Schesir',
    brand_logo_url: '/markalar/marca-logo-schesir.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_053.jpg', '/products/kopek/mama/kopek_mama_054.jpg'],
    tags: ['Konserve', 'Doğal', 'Tavuklu'],
    is_active: true,
    rating: 4.8,
    review_count: 312,
    features: ['Doğal Jöle', 'Saf Protein', 'Katkısız']
  },
  {
    id: 'p61',
    name: "Hill's Science Plan Küçük Irk Yetişkin 3kg",
    slug: 'hills-small-adult-3kg',
    description: 'Küçük ırk yetişkin köpekler için bilimsel formül. Sindirim ve enerji dengesi.',
    price: 890.00,
    discounted_price: 799.00,
    stock: 32,
    brand_id: 'hills',
    brand_name: "Hill's",
    brand_logo_url: '/marka_fotograflari/Hill_s/000001.jpg',
    category_id: 'kopek-mamasi',
    images: ['/products/kopek/mama/kopek_mama_220.jpg', '/products/kopek/mama/kopek_mama_221.jpg'],
    tags: ['Bilimsel', 'Küçük Irk', 'Yetişkin'],
    is_active: true,
    rating: 4.8,
    review_count: 276,
    features: ['Sindirim Sağlığı', 'Enerji Dengesi', 'Bilimsel']
  },

  // ===== YENİ KEDİ ÜRÜNLERİ (işlenmiş görseller) =====
  {
    id: 'p62',
    name: 'Royal Canin British Shorthair Adult 10kg',
    slug: 'royal-canin-british-shorthair-10kg',
    description: 'British Shorthair ırkı için özel formül. Kas yapısı ve kalp sağlığını destekler.',
    price: 2890.00,
    discounted_price: 2549.00,
    stock: 12,
    brand_id: 'royal-canin',
    brand_name: 'Royal Canin',
    brand_logo_url: '/marka_fotograflari/Royal%20Canin/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/products/kedi/mama/kedi_mama_001.jpg', '/products/kedi/mama/kedi_mama_002.jpg'],
    tags: ['Özel Irk', 'Premium', 'British Shorthair'],
    is_active: true,
    rating: 4.9,
    review_count: 187,
    features: ['Kas Yapısı', 'Kalp Sağlığı', 'Özel Irk']
  },
  {
    id: 'p63',
    name: "Hill's Science Plan Kitten Healthy Development 3kg",
    slug: 'hills-kitten-3kg',
    description: 'Yavru kediler için beyin ve görme gelişimini destekleyen bilimsel formül.',
    price: 890.00,
    discounted_price: 779.00,
    stock: 28,
    brand_id: 'hills',
    brand_name: "Hill's",
    brand_logo_url: '/marka_fotograflari/Hill_s/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/products/kedi/mama/kedi_mama_014.jpg', '/products/kedi/mama/kedi_mama_015.jpg'],
    tags: ['Yavru', 'Bilimsel', 'Gelişim'],
    is_active: true,
    rating: 4.8,
    review_count: 234,
    features: ['DHA', 'Beyin Gelişimi', 'Bağışıklık']
  },
  {
    id: 'p64',
    name: "Hill's Science Plan Adult Optimal Care 10kg",
    slug: 'hills-adult-optimal-10kg',
    description: 'Yetişkin kediler için optimal beslenme. Parlak tüy ve sağlıklı sindirim.',
    price: 2450.00,
    discounted_price: 2199.00,
    stock: 18,
    brand_id: 'hills',
    brand_name: "Hill's",
    brand_logo_url: '/marka_fotograflari/Hill_s/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/products/kedi/mama/kedi_mama_016.jpg', '/products/kedi/mama/kedi_mama_017.jpg'],
    tags: ['Yetişkin', 'Optimal', 'Bilimsel'],
    is_active: true,
    rating: 4.9,
    review_count: 412,
    features: ['Parlak Tüy', 'Sindirim Sağlığı', 'Optimal']
  },
  {
    id: 'p65',
    name: 'Pro Plan Sterilised Hindili Kedi Maması 10kg',
    slug: 'proplan-sterilised-hindi-10kg',
    description: 'Kısırlaştırılmış kediler için hindi etli formül. Kilo kontrolü ve böbrek sağlığı.',
    price: 2290.00,
    discounted_price: 1999.00,
    stock: 22,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/products/kedi/mama/kedi_mama_037.jpg', '/products/kedi/mama/kedi_mama_038.jpg'],
    tags: ['Kısırlaştırılmış', 'Hindi', 'Böbrek'],
    is_active: true,
    rating: 4.7,
    review_count: 356,
    features: ['OptiRenal', 'Kilo Kontrolü', 'Hindi Eti']
  },
  {
    id: 'p66',
    name: 'Pro Plan Elegant Somon Deri ve Tüy Bakım 10kg',
    slug: 'proplan-elegant-somon-10kg',
    description: 'Hassas deri ve tüyler için özel somon formülü. Omega yağları ve çinko.',
    price: 2390.00,
    discounted_price: 2099.00,
    stock: 16,
    brand_id: 'proplan',
    brand_name: 'Pro Plan',
    brand_logo_url: '/marka_fotograflari/Purina Pro Plan/000001.jpg',
    category_id: 'kedi-mamasi',
    images: ['/products/kedi/mama/kedi_mama_039.jpg', '/products/kedi/mama/kedi_mama_040.jpg'],
    tags: ['Deri Bakımı', 'Somon', 'Tüy Sağlığı'],
    is_active: true,
    rating: 4.8,
    review_count: 278,
    features: ['Omega 3-6', 'Parlak Tüy', 'Somon']
  },

  // ===== YENİ AKVARYUM ÜRÜNLERİ (işlenmiş görseller) =====
  {
    id: 'p67',
    name: 'Led Lambalı Bombeli Akvaryum Set 30x16x25cm',
    slug: 'led-bombeli-akvaryum-30cm',
    description: 'Şık bombeli tasarım, LED aydınlatma dahil. Başlangıç için ideal set.',
    price: 589.00,
    discounted_price: 499.00,
    stock: 20,
    brand_id: 'jungle',
    brand_name: 'Generic',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/products/akvaryum/tank/akvaryum_001.jpg', '/products/akvaryum/tank/akvaryum_002.jpg'],
    tags: ['Akvaryum', 'LED', 'Başlangıç'],
    is_active: true,
    rating: 4.5,
    review_count: 189,
    features: ['LED Işık', 'Bombeli Cam', 'Set']
  },
  {
    id: 'p68',
    name: 'Filtreli ve Işıklı Nano Akvaryum 50x15x36cm',
    slug: 'nano-akvaryum-filtreli-50cm',
    description: 'Modern nano akvaryum. Dahili filtre sistemi ve dokunmatik LED aydınlatma.',
    price: 1290.00,
    discounted_price: 1099.00,
    stock: 12,
    brand_id: 'jungle',
    brand_name: 'Generic',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/products/akvaryum/tank/akvaryum_005.jpg', '/products/akvaryum/tank/akvaryum_006.jpg'],
    tags: ['Nano', 'Filtreli', 'Modern'],
    is_active: true,
    rating: 4.7,
    review_count: 134,
    features: ['Dahili Filtre', 'Dokunmatik LED', 'Nano']
  },
  {
    id: 'p69',
    name: 'Marina Beta Akvaryum Seti EZ Care 2.5Lt',
    slug: 'marina-beta-ez-care-2-5lt',
    description: 'Beta balıkları için özel tasarım. Kolay su değişimi ve bakım sistemi.',
    price: 389.00,
    discounted_price: 329.00,
    stock: 35,
    brand_id: 'jungle',
    brand_name: 'Marina',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/products/akvaryum/tank/akvaryum_018.jpg', '/products/akvaryum/tank/akvaryum_019.jpg'],
    tags: ['Beta', 'Kolay Bakım', 'Mini'],
    is_active: true,
    rating: 4.6,
    review_count: 267,
    features: ['EZ Care', 'Kolay Su Değişimi', 'Beta']
  },
  {
    id: 'p70',
    name: 'Renkli Mini Fanus Akvaryum 4Lt',
    slug: 'renkli-mini-fanus-4lt',
    description: 'Dekoratif renkli kapak seçenekleri. Masaüstü için ideal mini akvaryum.',
    price: 289.00,
    discounted_price: 249.00,
    stock: 45,
    brand_id: 'jungle',
    brand_name: 'Generic',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/products/akvaryum/tank/akvaryum_007.jpg', '/products/akvaryum/tank/akvaryum_008.jpg'],
    tags: ['Mini', 'Dekoratif', 'Renkli'],
    is_active: true,
    rating: 4.4,
    review_count: 198,
    features: ['4 Litre', 'Renkli Kapak', 'Masaüstü']
  },
  {
    id: 'p71',
    name: 'Dijital Kaplumbağa Akvaryumu Filtreli',
    slug: 'dijital-kaplumbaga-akvaryumu',
    description: 'Su kaplumbağaları için özel tasarım. Filtre sistemi ve güneşlenme platformu dahil.',
    price: 789.00,
    discounted_price: 679.00,
    stock: 18,
    brand_id: 'jungle',
    brand_name: 'Generic',
    brand_logo_url: '/markalar/Group_135142.avif',
    category_id: 'akvaryum',
    images: ['/products/akvaryum/tank/akvaryum_023.jpg', '/products/akvaryum/tank/akvaryum_024.jpg'],
    tags: ['Kaplumbağa', 'Filtreli', 'Platform'],
    is_active: true,
    rating: 4.6,
    review_count: 145,
    features: ['Kaplumbağa', 'Platform', 'Filtre']
  }
];

// ==================== KAMPANYALAR ====================
export const CAMPAIGNS: Campaign[] = [
  // HERO SLIDER - Siyah tema köpek görselleri
  {
    id: 'slider1',
    title: 'Premium Köpek Serisi',
    image_url: '/banners/hero_dog_dark_01.png',
    target_url: '/kategori/kopek',
    location: 'slider'
  },
  {
    id: 'slider2',
    title: 'Özel Bakım Serisi',
    image_url: '/banners/hero_dog_dark_02.png',
    target_url: '/kategori/kopek',
    location: 'slider'
  },
  {
    id: 'slider3',
    title: 'Günlük Rutin Koleksiyonu',
    image_url: '/banners/hero_dog_dark_03.png',
    target_url: '/kategori/kopek',
    location: 'slider'
  },
  // PROMO BANNERS - Yeni üretilen görseller
  {
    id: 'promo1',
    title: 'Premium Kedi Mamaları',
    image_url: '/banners/hero_cat.png',
    target_url: '/kategori/kedi',
    location: 'promo'
  },
  {
    id: 'promo2',
    title: 'Yavru Kedi Ürünleri',
    image_url: '/banners/hero_kitten.png',
    target_url: '/kategori/kedi',
    location: 'promo'
  },
  {
    id: 'promo3',
    title: 'Köpek Dostlarınız İçin',
    image_url: '/banners/hero_golden.png',
    target_url: '/kategori/kopek',
    location: 'promo'
  },
  {
    id: 'promo4',
    title: 'Yavru Köpek Bakımı',
    image_url: '/banners/hero_puppy.png',
    target_url: '/kategori/kopek',
    location: 'promo'
  },
  {
    id: 'promo5',
    title: 'Akvaryum & Balık Dünyası',
    image_url: '/banners/hero_fish.png',
    target_url: '/kategori/balik',
    location: 'promo'
  },
  {
    id: 'cp6',
    title: 'Kuş Dünyası - En İyi Yem ve Kafesler',
    image_url: '/banners/kategori_kus.png',
    target_url: '/kategori/kus',
    location: 'category'
  },
  {
    id: 'cp7',
    title: 'Balık & Akvaryum - Premium Ürünler',
    image_url: '/banners/kategori_balik.png',
    target_url: '/kategori/balik',
    location: 'category'
  },
  {
    id: 'cp8',
    title: 'Kemirgen Dünyası - Sağlıklı Yaşam',
    image_url: '/banners/kategori_kemirgen.png',
    target_url: '/kategori/kemirgen',
    location: 'category'
  },
  {
    id: 'cp9',
    title: 'Evcil Hayvan Besleme Rehberi',
    image_url: '/banners/blog_besleme.png',
    target_url: '/blog',
    location: 'blog'
  }
];

// ==================== YORUMLAR ====================
export const PRODUCT_REVIEWS = [
  { id: 'r1', user: 'Zeynep K.', rating: 5, date: '12 Ocak 2026', comment: 'Kedim bayılarak yiyor, tüyleri daha parlak oldu.' },
  { id: 'r2', user: 'Caner T.', rating: 4, date: '05 Ocak 2026', comment: 'Hızlı kargo ve taze ürün, teşekkürler.' },
  { id: 'r3', user: 'Elif D.', rating: 5, date: '28 Aralık 2025', comment: 'Köpeğimin favorisi oldu, tavsiye ederim.' },
  { id: 'r4', user: 'Murat Y.', rating: 5, date: '20 Aralık 2025', comment: 'Orijinal ürün garantisi çok önemli, güvenle alışveriş yaptım.' },
];

// ==================== BLOG YAZILARI ====================
export const BLOG_POSTS = [
  { id: 'bp1', title: 'Yavru Kedi Beslenmesinde 5 Altın Kural', img: '/banners/blog_kitten.png' },
  { id: 'bp2', title: 'Köpeklerde Eklem Sağlığı ve Önemi', img: '/banners/blog_dog.png' },
  { id: 'bp3', title: 'Tahılsız Mamalar Hakkında Bilinmeyenler', img: '/banners/blog_grain.png' },
  { id: 'bp4', title: 'Kedi Kumu Seçiminde Dikkat Edilmesi Gerekenler', img: '/banners/blog_litter.png' },
];

// ==================== MOCK SİPARİŞLER ====================
export const MOCK_ORDERS = [
  { id: 'ORD-001', user_id: 'u1', customer_name: 'Ahmet Yılmaz', customer_email: 'ahmet@email.com', customer_phone: '0532 111 2233', total_price: 1649.00, status: 'Hazırlanıyor' as const, address_info: 'Kadıköy, İstanbul', created_at: '2026-01-07' },
  { id: 'ORD-002', user_id: 'u2', customer_name: 'Ayşe Demir', customer_email: 'ayse@email.com', customer_phone: '0533 222 3344', total_price: 899.00, status: 'Kargolandı' as const, address_info: 'Çankaya, Ankara', created_at: '2026-01-06' },
  { id: 'ORD-003', user_id: 'u3', customer_name: 'Mehmet Kaya', customer_email: 'mehmet@email.com', customer_phone: '0534 333 4455', total_price: 2450.00, status: 'Teslim Edildi' as const, address_info: 'Bornova, İzmir', created_at: '2026-01-05' },
];

export const PET_DEMOGRAPHICS = [
  { breed: 'Golden Retriever', percentage: 42 },
  { breed: 'Tekir Kedi', percentage: 38 },
  { breed: 'Pug', percentage: 20 },
];
